### ISSUE TITLE
Fix code scanning alert - Incorrect conversion between integer types

### ISSUE THREAD

**Issue by OleDakotaJoe** [OleDakotaJoe/clonr#55]
Tracking issue for:
- [ ] https://github.com/OleDakotaJoe/clonr/security/code-scanning/1

**Comment by Ayrtat** [comment]
> Tracking issue for:
> 
> * [ ]  https://github.com/OleDakotaJoe/clonr/security/code-scanning/1

Hi! This links seems to be invalid (404)

**Comment by OleDakotaJoe** [comment]
Hi! Awesome that you responded!

Seems that it's a permissions issue. 
Let me see if I can give you permission

**Comment by OleDakotaJoe** [comment]
@Ayrtat, just added you as a collaborator lemme know if you have any questions!

**Comment by Ayrtat** [comment]
> @Ayrtat, just added you as a collaborator lemme know if you have any questions!

Nah... I have got notification that you included me as a collaborator but I still cannot visit the link :(

**Comment by Ayrtat** [comment]
Sorry! I just forgot to accept invitation. I am able to watch the ticket!

**Comment by OleDakotaJoe** [comment]
😄 
Hey, so this is a really small ticket, but I wanted to be sure that I was able to share some knowledge. 

I'll send you a link to a discord server.

**Comment by Ayrtat** [comment]
> smile Hey, so this is a really small ticket, but I wanted to be sure that I was able to share some knowledge.
> 
> I'll send you a link to a discord server.

Alright. Let me have ramble the project files to take a common figuration. When I get questions, I'll contact with you!

**Comment by OleDakotaJoe** [comment]
Thanks @Ayrtat  for your help on this! the PR was merged, and all of the post-merge automation + security checks passed
